version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - private

  backend-app:
    container_name: backend-app
    image: edutie/backend-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DOMAIN_HOSTNAME}:host-gateway"
    depends_on:
      - db
      - keycloak
    networks:
      - private
      - public

  llm-service:
    container_name: llm-service
    image: edutie/llm-service
    build: ../edutie-llm
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-llm:/app
    ports:
      - "9000:80"
    env_file:
      - .env
    networks:
      - private

  knowledge-map-service:
    container_name: knowledge-map-service
    build:
      context: ../edutie-knowledge-map
      dockerfile: Dockerfile
    image: edutie/knowledge-map-service
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-knowledge-map:/app
    env_file:
      - .env
    ports:
      - "9001:80"
    networks:
      - private

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    env_file:
      - .env
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ../edutie-authorization-server/import/:/opt/keycloak/data/import/
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DOMAIN_HOSTNAME}:host-gateway"
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - private

  bff:
    container_name: bff
    image: edutie/bff
    env_file:
      - .env
    build:
      context: ../edutie-bff
      dockerfile: Dockerfile
    ports:
      - "7081:7081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DOMAIN_HOSTNAME}:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - public
      - private

  api-gateway:
    container_name: api-gateway
    image: edutie/api-gateway
    env_file:
      - .env
    build:
      context: ../edutie-api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - public
      - private

  frontend-app:
    container_name: frontend-app
    image: edutie/frontend-app
    build:
      context: ../edutie-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DOMAIN_HOSTNAME}:host-gateway"
    volumes:
      - ../edutie-frontend/node_modules:/app/node_modules
      - ../edutie-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public

  website:
    image: node:16.15.0-alpine
    container_name: website
    working_dir: /app
    volumes:
      - ../edutie.nowanauka.pl:/app
    command: /bin/sh -c "chown -R 1000:1001 /root/.npm && npm start"
    expose:
      - "8080"
    networks:
      - public

networks:
  private:
    driver: bridge
  public:
    driver: bridge

volumes:
  maven-repo: