version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - backendnetwork

  backendapp:
    container_name: backend-app
    image: edutie/backend-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    depends_on:
      - db
      - keycloak
    networks:
      - backendnetwork
      - frontendnetwork

  llmservice:
    container_name: llm-service
    image: edutie/llm-service
    build: ../edutie-llm
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-llm:/app
    ports:
      - "9000:80"
    env_file:
      - ../edutie-llm/.env
    networks:
      - backendnetwork

  wikimapservice:
    build: ../edutie-wikimap
    image: edutie/wikimap-service
    container_name: wikimap-service
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-wikimap:/app
    ports:
      - "9001:80"
    networks:
      - backendnetwork

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    env_file:
      - ../edutie-authorization-server/.env
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ../edutie-authorization-server/import/:/opt/keycloak/data/import/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backendnetwork

#TODO: change network naming
networks:
  backendnetwork:
    name: backendnetwork
  frontendnetwork:
    name: frontendnetwork

volumes:
  maven-repo: