version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - backendnetwork

  backendapp:
    container_name: backendapp
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    depends_on:
      - db
      - keycloak
    networks:
      - backendnetwork

  llmservice:
    container_name: llmservice
    build: ../edutie-llm
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ../edutie-llm:/app
    ports:
      - "9000:80"
    env_file:
      - ../edutie-llm/.env
    networks:
      - backendnetwork

  wikimapservice:
    build: ../edutie-wikimap
    container_name: wikimapservice
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ../edutie-wikimap:/app
    ports:
      - "9001:80"
    depends_on:
      - knowledgemapdb
    networks:
      - backendnetwork

  knowledgemapdb: # This will be deleted in the future. Future implementation will utilize edutie DB
    container_name: knowledgemapdb
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5436:5432'
    networks:
      - backendnetwork

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    command:
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
    volumes:
      - ../edutie-authorization-server/import/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8080/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080/auth
      KC_HTTP_RELATIVE_PATH: /auth
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backendnetwork

networks:
  backendnetwork:
    name: backendnetwork

volumes:
  maven-repo: