version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - private

  backend-app:
    container_name: backend-app
    image: edutie/backend-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    depends_on:
      - db
      - keycloak
    networks:
      - private
      - public

  llm-service:
    container_name: llm-service
    image: edutie/llm-service
    build: ../edutie-llm
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-llm:/app
    ports:
      - "9000:80"
    env_file:
      - ../edutie-llm/.env
    networks:
      - private

  knowledge-map-service:
    container_name: knowledge-map-service
    image: edutie/knowledge-map-service
    build: ../edutie-knowledge-map
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ../edutie-knowledge-map:/app
    ports:
      - "9001:80"
    networks:
      - private

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    env_file:
      - .env
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ../edutie-authorization-server/import/:/opt/keycloak/data/import/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - private

  frontend-app:
    container_name: frontend-app
    image: edutie/frontend-app
    build:
      context: ../edutie-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../edutie-frontend/node_modules:/app/node_modules
      - ../edutie-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public

networks:
  private:
    driver: bridge
  public:
    driver: bridge

volumes:
  maven-repo:
