version: "3.0"
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    container_name: db

  service:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db