version: "3.0"
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#      - ./init:/docker-entrypoint-initdb.d/
    container_name: db

  service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    depends_on:
      - db

volumes:
  maven-repo: