version: "3.0"
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - backendnetwork

  backendapp:
    container_name: backendapp
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_REPO=/maven-repo
    ports:
      - "8081:8081"
    volumes:
      - maven-repo:/root/.m2/repository
    depends_on:
      - db
    networks:
      - backendnetwork

networks:
  backendnetwork:
    name: backendnetwork

volumes:
  maven-repo: