server:
  port: 8081


spring:
  cert: http://localhost:8080/auth/realms/edutie/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: login-app
#            authorization-grant-type: authorization_code
#            scope: openid
#            client-name: keycloak
#            provider: keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://52.32.178.153:8080/realms/SpringBootKeycloak
#            user-name-attribute: preferred_username
#      resource-server:
#        jwt:
#          issuer-uri: http://52.32.178.153:8080/realms/SpringBootKeycloak

springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
    path: /v1/docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger
    enabled: true
  writer-with-default-pretty-printer: true
  group-configs:
    -
      group: Learning
      packages-to-scan:
        - com.edutie.backend.api.v1.learning
    -
      group: Management
      packages-to-scan:
        - com.edutie.backend.api.v1.management
