# ==== EXTERNAL SERVICES URLs ====
knowledge-map-url: ${KNOWLEDGE_MAP_URL}
llm-service-url: ${LLM_SERVICE_URL}
# Main url for host (reverse proxy) - used for app origin (CORS handling)
host-main-url: ${HOST_MAIN_URL}

# ==== SERVER CONFIG ====
server:
  port: 8081

# ==== SPRING BOOT CONFIG ====
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  jpa:
    hibernate:
      ddl-auto: ${DB_MODE}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER}

# ==== AUTH CONFIG ====
authorization-url: ${AUTHORIZATION_URL}
token-url: ${TOKEN_URL}
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${TOKEN_ISSUER}
            jwk-set-uri: ${JWT_KEY_LOCATION}
            username-claim: $.preferred_username
            authorities:
              - path: $.realm_access.roles
            aud:
        resourceserver:
          permit-all:
            - /**

# ==== BASIC SPRING LOGGING ====
logging:
  level:
    web: debug

# ==== SWAGGER CONFIG ====
springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
    path: /docs/spec
    groups:
      enabled: true
  swagger-ui:
    path: /docs
    enabled: true
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      scopes:
        - openid
  writer-with-default-pretty-printer: true
  group-configs:
    - group: Learning
      packages-to-scan:
        - com.edutie.backend.api.v1.learning
    - group: Management
      packages-to-scan:
        - com.edutie.backend.api.v1.management
    - group: Profiles
      packages-to-scan:
        - com.edutie.backend.api.v1.profiles
    - group: Testing
      packages-to-scan:
        - com.edutie.backend.api.v1.testing
  show-actuator: true
  show-login-endpoint: true
  show-oauth2-endpoints: true
  show-spring-cloud-functions: true
