name: build-and-push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Build the Docker image
        run: docker build -t edutie-backend ./
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}xยง
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: .//Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/edutie-backend:latest